<?php

/**
 * Copyright © Monsoon Consulting. All rights reserved.
 * See LICENSE_MONSOON.txt for license details.
 */

declare(strict_types=1);

use Monsoon\HyvaAjaxAddToCart\Block\AddToCart;
use Magento\Framework\Escaper;

/**
 * @var AddToCart $block
 * @var Escaper $escaper
 */

// phpcs:ignoreFile Generic.Files.LineLength.TooLong
?>
<style>
    .is-loading> :not(.loader) {
        visibility: hidden;
    }
</style>

<script>
    window.setAjaxCart = (selectors = '.product_addtocart_form, #product_addtocart_form', recursive = true) => {
        const addToCartForms = document.querySelectorAll(selectors);
        const delay = parseInt('<?= $escaper->escapeJs($block->getDelay()) ?>', 10);

        addToCartForms.forEach(form => {
            form.addEventListener('submit', async e => {
                e.preventDefault();
                const data = new URLSearchParams(new FormData(form)),
                    button = form.querySelector('button') ?
                    form.querySelector('button') :
                    document.getElementById('product-addtocart-button'),
                    loader = document.createElement('div');

                loader.className = 'absolute inset-0 flex justify-center items-center loader';

                loader.innerHTML = `
                <svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="32" height="32" viewBox="0 0 128 128" xml:space="preserve">
                    <g>
                        <circle cx="16" cy="64" r="4" fill="#fff"/>
                        <circle cx="16" cy="64" r="8" fill="#fff" transform="rotate(45 64 64)"/>
                        <circle cx="16" cy="64" r="12" fill="#fff" transform="rotate(90 64 64)"/>
                        <circle cx="16" cy="64" r="16" fill="#fff" transform="rotate(135 64 64)"/>
                        <animateTransform attributeName="transform" type="rotate" values="45 64 64;90 64 64;135 64 64;180 64 64;225 64 64;270 64 64;315 64 64;0 64 64" calcMode="discrete" dur="960ms" repeatCount="indefinite"/>
                    </g>
                </svg>
                `;

                button.prepend(loader);
                button.classList.add('relative', 'is-loading', 'overflow-hidden');
                button.disabled = true;


                const productIdInput = form.querySelector('input[name="product"]');
                const productId = productIdInput ? parseInt(productIdInput.value) : null;

                const restrictionResult = await Alpine.store('estateApi').checkProductRestriction(productId, null);
                if (restrictionResult !== 1) {
                    if (loader && loader.parentNode) {
                        loader.remove();
                    }
                    button.classList.remove('relative', 'is-loading', 'overflow-hidden');
                    button.disabled = false;
                    return;
                }
                const restrictionResultage = await Alpine.store('stateAgeApi').check(productId);
                if (restrictionResultage !== 1) {
                    if (loader && loader.parentNode) {
                        loader.remove();
                    }
                    button.classList.remove('relative', 'is-loading', 'overflow-hidden');
                    button.disabled = false;
                    return;
                }

                fetch(form.action, {
                        method: 'POST',
                        body: data,
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
                            'X-Requested-With': 'XMLHttpRequest'
                        }
                    })
                    .then(res => {
                        console.log('Fetch response status:', res.status, res.ok, res.redirected);

                        if (!res.ok) {
                            return form.submit();
                        }

                        if (res.redirected) {
                            return [];
                        }

                        return res.json();
                    })
                    .then(data => {
                        if (data.backUrl) {
                            form.submit();
                        }

                        if (recursive) {
                            window.dispatchEvent(new CustomEvent('product-addtocart-success'));
                        }

                        window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                    })
                    .catch(err => {
                        window.dispatchEvent(new CustomEvent('product-addtocart-error'));

                        setMessage({
                            text: '<?= $escaper->escapeHtml(__('There was a problem adding your item to the cart.')) ?>',
                            type: 'error'
                        });
                    })
                    .finally(() => {
                        try {
                            var messages = hyva.getCookie('mage-messages');
                            messages = messages ? JSON.parse(decodeURIComponent(messages).replace(/\+/g, ' ')) : [];
                            document.cookie = 'mage-messages=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';

                        } catch (error) {
                            console.warn('Error parsing Cookie Messages:', error);
                            return;
                        }
                        setTimeout(() => {
                            loader.remove();
                            button.classList.remove('is-loading');
                            button.disabled = false;
                            window.dispatchEvent(new CustomEvent("toggle-cart"));
                            messages.forEach(message => {
                                setMessage(message);
                            });
                        }, delay);
                    });
            });
        });
    }

    /**
     * Set Message
     */
    function setMessage(message) {
        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
            [message], 5000
        );
    }

    /** Init on pageload */
    window.setAjaxCart();
</script>

<!-- buy now functionality -->
<script>
    window.setAjaxBuyNow = (selectors = '.product_addtocart_form, #product_addtocart_form', recursive = true) => {
        const addToCartForms = document.querySelectorAll(selectors);
        const delay = parseInt('<?= $escaper->escapeJs($block->getDelay()) ?>', 10);
        addToCartForms.forEach(async form => {
            const data = new URLSearchParams(new FormData(form));
            const button = document.getElementById('ahy-buy-now-button');
            const loader = document.createElement('div');

            loader.className = 'absolute inset-0 flex justify-center items-center loader';
            loader.innerHTML = `
                <svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="32" height="32" viewBox="0 0 128 128" xml:space="preserve">
                    <g>
                        <circle cx="16" cy="64" r="4" fill="#fff"/>
                        <circle cx="16" cy="64" r="8" fill="#fff" transform="rotate(45 64 64)"/>
                        <circle cx="16" cy="64" r="12" fill="#fff" transform="rotate(90 64 64)"/>
                        <circle cx="16" cy="64" r="16" fill="#fff" transform="rotate(135 64 64)"/>
                        <animateTransform attributeName="transform" type="rotate"
                            values="45 64 64;90 64 64;135 64 64;180 64 64;225 64 64;270 64 64;315 64 64;0 64 64"
                            calcMode="discrete" dur="960ms" repeatCount="indefinite"/>
                    </g>
                </svg>
            `;

            const buttonInnerText = button.innerHTML;
            button.innerHTML = '';
            button.classList.add('relative', 'is-loading', 'cursor-not-allowed');
            button.disabled = true;
            button.prepend(loader);

            const productIdInput = form.querySelector('input[name="product"]');
            const productId = productIdInput ? parseInt(productIdInput.value) : null;

            if (!productId || isNaN(productId)) {
                loader.remove();
                button.innerHTML = buttonInnerText;
                button.classList.remove('is-loading', 'cursor-not-allowed');
                button.disabled = false;
                return;
            }

            const restrictionResult = await Alpine.store('estateApi').checkProductRestriction(productId, null);
            if (restrictionResult !== 1) {
                loader.remove();
                button.classList.remove('relative', 'is-loading', 'cursor-not-allowed');
                button.innerHTML = buttonInnerText;
                button.disabled = false;
                return;
            }
            const restrictionResultage = await Alpine.store('stateAgeApi').check(productId);
            if (restrictionResultage !== 1) {
                if (loader && loader.parentNode) {
                    loader.remove();
                }
                button.classList.remove('relative', 'is-loading',  'cursor-not-allowed');
                 button.innerHTML = buttonInnerText;
                button.disabled = false;
                return;
            }
            fetch(form.action, {
                    method: 'POST',
                    body: data,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                })
                .then(res => {
                    if (!res.ok) {
                        return form.submit();
                    }

                    if (res.redirected) {
                        return [];
                    }

                    return res.json();
                })
                .then(data => {
                    if (data.backUrl) {
                        form.submit();
                    }

                    if (recursive) {
                        window.dispatchEvent(new CustomEvent('product-addtocart-success'));
                    }

                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                })
                .catch(err => {
                    window.dispatchEvent(new CustomEvent('product-addtocart-error'));
                    setMessage({
                        text: '<?= $escaper->escapeHtml(__('There was a problem adding your item to the cart.')) ?>',
                        type: 'error'
                    });
                })
                .finally(() => {
                    try {
                        let messages = hyva.getCookie('mage-messages');
                        messages = messages ? JSON.parse(decodeURIComponent(messages).replace(/\+/g, ' ')) : [];
                        document.cookie = 'mage-messages=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
                    } catch (error) {
                        console.warn('Error parsing Cookie Messages:', error);
                    }

                    setTimeout(() => {
                        loader.remove();
                        button.classList.remove('is-loading', 'cursor-not-allowed');
                        button.disabled = false;
                        button.innerHTML = buttonInnerText;
                        window.location.href = '/checkout/';
                    }, delay);
                });
        });
    };
</script>